### PR TITLE
autorelease.sh: add `set -euo pipefail`, clean up on failure

### PR DESCRIPTION
**Pull request by zhenyavinogradov**
Add stricter failure checks and remove temporary files

### CODE REVIEW

**Comment by zhenyavinogradov** [comment]
It was failing if the release did not exist before, now it's fixed

**Comment by zhenyavinogradov** [comment]
The script failed randomly, but worked after a retry, I don't know why: https://buildkite.com/serokell/tezos-packaging/builds/253#45ea1d1b-0316-4b46-890d-48b530ba86af

**Comment by yorickvP** [comment]
Duplicate value for 'name'. Maybe some of the github servers have a constraint for it?

**Comment by zhenyavinogradov** [comment]
If the error happened when attaching an asset to the release, it would mean there already was an asset with the same name, which github does prohibit. But it does not make sense why it would occur for a just created release. It's also confusing that `hub` says 4 assets failed to upload but shows a single error response

**Pull request merged**
