### PR TITLE
v8.0-rc2

### PR DESCRIPTION
**Pull request by rvem**
## Description

A new v8.0 release candidate arrived. New version supports new protocol, so we'd like
to make a release for this release candidate version.

This PR updates only docker based static binaries and nix binaries. Native packages aren't updated because
v8.0-rc2 tezos packages aren't presented in the opam repository.

~Depends on https://github.com/serokell/opam-nix/pull/2~

## Related issue(s)

Relates #26 

#### Related changes (conditional)

- [x] I checked whether I should update the [README](../tree/master/README.md)

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).

### CODE REVIEW

**Comment by balsoft** [comment]
I merged opam-nix PR, please repin

**Comment by balsoft** [comment]
What can and can't be built statically now? I need some static libraries from here in Ligo.

**Comment by rvem** [comment]
Well, the main problem is that it is impossible to compile any rust libraries.
Everything else should work

**Comment by rvem** [comment]
Specifically, looks like everything starting from 006 protocol depends on rust now

**Review by balsoft — APPROVED** [review]
We need to fix static nix stuff at some point, but for now LGTM

**Pull request merged**
